Suppress -Wunnecessary-virtual-specifier
With clang update, building code using llvm-project headers from older
version triggers the following build errors:

In file included from external/mesa3d/src/gallium/auxiliary/gallivm/lp_bld_misc.cpp:73:
In file included from external/swiftshader/third_party/llvm-16.0/llvm/include/llvm/IR/IRBuilder.h:24:
external/swiftshader/third_party/llvm-16.0/llvm/include/llvm/IR/ConstantFolder.h:31:16: error: virtual method 'anchor' is inside a 'final' class and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
   31 |   virtual void anchor();
      |                ^

So suppress -Wunnecessary-virtual-specifier when llvm-project headers
are used.

Bug: 452729455
Test: build with clang update
Change-Id: I5beab62034cdd9cb6cf3778310597bdbf2704f39