Revert "Merge commit upstream-mesa-26.1.4 into emu-main-dev"
This reverts commit 3f2f1b41d9a77ffff69dfa6174961ea8f52d9285.

Reason for revert: breaks the build

18:29:51 external/mesa3d+/src/compiler/spirv/spirv_to_nir.c:7674:47: error: use of undeclared identifier 'num_spec'
18:29:51  7674 |                                         spec, num_spec,
Bug: 527073832
Change-Id: I58982d779202a60e8298dadc748d401f76986cb8